#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TwitterSearch.Resource", IsApplication=true)]

namespace TwitterSearch
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int light_orange = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050001
			public const int editButtonWidth = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int tagButtonWidth = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int btnClearTags = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int btnEdit = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int btnSave = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int btnSavedTag = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int newTagTableRow = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int queryScrollView = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int searchResultTableLayout = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int tableLayout = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int tableRow1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int tableRow2 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int tableRow3 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int tableRow4 = 2131165192;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow5 = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int textView8 = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int txtSearchQuery = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int txtTagQuery = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SavedTags = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int Cancel = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int ClearTags = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int ConfirmMessage = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int ConfirmTitle = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int Edit = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int Erase = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int MissingMessage = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int MissingTitle = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int OK = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int QueryPrompt = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int Save = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int SearchUrl = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int TagPrompt = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int TagggedSearches = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
